### ISSUE TITLE
Doesn't run in Git for Windows Bash shell

### ISSUE THREAD

**Issue by SteveALee** [senecajs/seneca-in-practice#13]
Seems to be a problem with the stdin

<pre>
C:\Users\Steve\AppData\Roaming\nvm\v4.1.0\node_modules\seneca-in-practice\node_modules\workshopper\node_modules\terminal-menu\index.js:61
    process.stdin.setRawMode(true);
                  ^

TypeError: process.stdin.setRawMode is not a function
    at new Menu (C:\Users\Steve\AppData\Roaming\nvm\v4.1.0\node_modules\seneca-in-practice\node_modules\workshopper\node_modules\terminal-menu\index.js:61:19)
    at module.exports (C:\Users\Steve\AppData\Roaming\nvm\v4.1.0\node_modules\seneca-in-practice\node_modules\workshopper\node_modules\terminal-menu\index.js:8:12)
    at showMenu (C:\Users\Steve\AppData\Roaming\nvm\v4.1.0\node_modules\seneca-in-practice\node_modules\workshopper\menu.js:14:18)
    at Workshopper.printMenu (C:\Users\Steve\AppData\Roaming\nvm\v4.1.0\node_modules\seneca-in-practice\node_modules\workshopper\workshopper.js:311:14)
    at new Workshopper (C:\Users\Steve\AppData\Roaming\nvm\v4.1.0\node_modules\seneca-in-practice\node_modules\workshopper\workshopper.js:158:8)
    at Workshopper (C:\Users\Steve\AppData\Roaming\nvm\v4.1.0\node_modules\seneca-in-practice\node_modules\workshopper\workshopper.js:20:12)
    at Object.<anonymous> (C:\Users\Steve\AppData\Roaming\nvm\v4.1.0\node_modules\seneca-in-practice\runners.js:13:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
</pre>

Also running "winpty Seneca-in-practice" to get better terminal emulation returns 

<pre>
Error @2 starting Seneca-in-practice
</pre>

**Comment by GlenTiki** [comment]
What version of node are you trying to run this on? This issue seems to be related to https://github.com/substack/terminal-menu/issues/25

**Comment by SteveALee** [comment]
I tried both 0.10.40 (x32) and then 4.1.0 (x64) as I suspected a node version issue given the error

I'm using nvm-windows to switch but that is most unlikely to cause this issue.

**Comment by SteveALee** [comment]
Well it seems it should work. The following in a node 4.1.0 REPL in GfW Bash:

<pre>
> process.stdin.isTTY
true
> process.stdin.setRawMode
[Function]
</pre>

So perhaps the workshopper or terminal-menu modules are doing something weird?

**Comment by marcopiraccini** [comment]
Well, the error is from `terminal-menu`. It seems something related  with this: https://github.com/nodejs/node/issues/2333 
Can you try other workshopper (e.g. learnyounode) with the same node /os set to confirm that?

**Comment by piccoloaiutante** [comment]
Have you tried to run it in powershell?

**Comment by SteveALee** [comment]
> Have you tried to run it in powershell?

Yes it's fine, and also in cmd shell. 
I can use it, just not in the Bash shell I sit in all day. Fee free to close this as "won't fix". :)

**Comment by marcopiraccini** [comment]
Just for curiosity...which shell are you using? This one? http://win-bash.sourceforge.net/

**Comment by SteveALee** [comment]
No. It's the one that comes with [Git for Windows](https://git-for-windows.github.io/). I'm not sure what exactly it is but it certainly appears that it's parentage is [MinGW/MSYS](http://mingw.org/). GitHub for windows also uses a version but I found that has been left behind Git for Windows.

**Comment by SteveALee** [comment]
Ah yes, they appear to be pulling upstream from CVS.
