### ISSUE TITLE
Step 'Client': Plugin Not Found error

### ISSUE THREAD

**Issue by batjko** [senecajs/seneca-in-practice#25]
Hi there,

I have just tried to do the second step, 'Client', but I keep getting this error, which seems to say it can't find the 'math' plugin.
But the error stack also says that the action pattern could not be found (`No matching action pattern found`).

This is on Win7, with Node 5.7 installed and Seneca 1.3.0.

I'll post the two code files first and the extremely verbose error stack at the bottom. Any ideas?

``` js
//math.js
const seneca = require('seneca')()

seneca.add( 'role:math,cmd:sum', function( msg, respond ) {
       const result = msg.left + msg.right;
       respond( null, { answer: result });
   });

module.exports = seneca
```

``` js
// mathclient.js
const seneca = require('seneca')();

seneca.use('math');
//console.dir(process.argv);

seneca.act({role: 'math', cmd: 'sum', left: 15, right: 30}, function (err, result) {
  if (err) return console.error (err)
  console.log(result)
});

```

When I run either `node mathclient.js` or the full `seneca-in-practice run mathclient.js`, I get this monstrosity of an error (which I have already cut in half by removing the system details):

``` shell
{ [Error: seneca: No matching action pattern found for { role: 'math', cmd: 'sum', left: 15, right: 28 }, and no default result provided (using a default$ property).]
  eraro: true,
  orig: null,
  code: 'act_not_found',
  seneca: true,
  package: 'seneca',
  msg: 'seneca: No matching action pattern found for { role: \'math\', cmd: \'sum\', left: 15, right: 28 }, and no default result provided (using a default$ property).',
  details:
   { args: '{ role: \'math\', cmd: \'sum\', left: 15, right: 28 }',
     plugin: {} },
  callpoint: 'at Object.execute_action [as fn] (C:\\Users\\tthpmx\\AppData\\Roaming\\npm\\node_modules\\seneca-in-practice\\node_modules\\seneca\\seneca.js:1054:29)' }
{ [Error: seneca: No matching action pattern found for { role: 'math', cmd: 'sum', left: 15, right: 30 }, and no default result provided (using a default$ property).]
  eraro: true,
  orig: null,
  code: 'act_not_found',
  seneca: true,
  package: 'seneca',
  msg: 'seneca: No matching action pattern found for { role: \'math\', cmd: \'sum\', left: 15, right: 30 }, and no default result provided (using a default$ property).',
  details:
   { args: '{ role: \'math\', cmd: \'sum\', left: 15, right: 30 }',
     plugin: {} },
  callpoint: 'at Object.execute_action [as fn] (c:\\Git\\seneca-practice\\node_modules\\seneca\\seneca.js:1054:29)' }


Seneca Fatal Error
==================

Message: seneca: use-plugin: Could not load plugin c:\Git\seneca-practice/mathclient.js; require search list: c:\Git\seneca-practice/mathclient.js, seneca-c:\Git\seneca-practice/mathclient.js, ./c:\Git\seneca-practice/mathclient.js, ./seneca-c:\Git\seneca-practice/mathclient.js.

Code: plugin_not_found

Details: { 'orig$':
   { [Error: use-plugin: Could not load plugin c:\Git\seneca-practice/mathclient.js; require search list: c:\Git\seneca-practice/mathclient.js, seneca-c:\Git\seneca-practice/mathclient.js, ./c:\Git\seneca-practice/mathclient.js, ./seneca-c:\Git\seneca-practice/mathclient.js.]
     eraro: true,
     orig: null,
     code: 'not_found',
     'use-plugin': true,
     package: 'use-plugin',
     msg: 'use-plugin: Could not load plugin c:\\Git\\seneca-practice/mathclient.js; require search list: c:\\Git\\seneca-practice/mathclient.js, seneca-c:\\Git\\seneca-practice/mathclient.js, ./c:\\Git\\seneca-practice/mathclient.js, ./seneca-c:\\Git\\seneca-practice/mathclient.js.',
     details:
      { options: {},
        callback: undefined,
        history:
         [ { module: 'C:\\Users\\tthpmx\\AppData\\Roaming\\npm\\node_modules\\seneca-in-practice\\node_modules\\seneca\\seneca.js',
             path: 'c:\\Git\\seneca-practice/mathclient.js' } ],
        name: 'c:\\Git\\seneca-practice/mathclient.js',
        search:
         [ { type: 'normal',
             name: 'c:\\Git\\seneca-practice/mathclient.js' },
           { type: 'normal',
             name: 'seneca-c:\\Git\\seneca-practice/mathclient.js' },
           { type: 'normal',
             name: './c:\\Git\\seneca-practice/mathclient.js' },
           { type: 'normal',
             name: './seneca-c:\\Git\\seneca-practice/mathclient.js' } ],
        modulepath: 'C:\\Users\\tthpmx\\AppData\\Roaming\\npm\\node_modules\\seneca-in-practice\\node_modules\\seneca\\seneca.js',
        requirepath: 'c:\\Git\\seneca-practice/mathclient.js',
        found:
         { type: 'normal',
           name: 'c:\\Git\\seneca-practice/mathclient.js' },
        init: {},
        searchlist: 'c:\\Git\\seneca-practice/mathclient.js, seneca-c:\\Git\\seneca-practice/mathclient.js, ./c:\\Git\\seneca-practice/mathclient.js, ./seneca-c:\\Git\\seneca-practice/mathclient.js' },
     callpoint: 'at Seneca.api_use [as use] (C:\\Users\\tthpmx\\AppData\\Roaming\\npm\\node_modules\\seneca-in-practice\\node_modules\\seneca\\seneca.js:963:29)' },
  'message$': 'use-plugin: Could not load plugin c:\\Git\\seneca-practice/mathclient.js; require search list: c:\\Git\\seneca-practice/mathclient.js, seneca-c:\\Git\\seneca-practice/mathclient.js, ./c:\\Git\\seneca-practice/mathclient.js, ./seneca-c:\\Git\\seneca-practice/mathclient.js.' }

Stack:
    at errormaker (C:\Users\tthpmx\AppData\Roaming\npm\node_modules\seneca-in-practice\node_modules\eraro\eraro.js:94:15)
    at Object.use (C:\Users\tthpmx\AppData\Roaming\npm\node_modules\seneca-in-practice\node_modules\use-plugin\use.js:94:13)
    at Seneca.api_use [as use] (C:\Users\tthpmx\AppData\Roaming\npm\node_modules\seneca-in-practice\node_modules\seneca\seneca.js:963:29)
    at Object.<anonymous> (C:\Users\tthpmx\AppData\Roaming\npm\node_modules\seneca-in-practice\problems\client\seneca-client-executor.js:8:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
```

**Comment by batjko** [comment]
So I noticed that it works just fine when executed with Node:
![image](https://cloud.githubusercontent.com/assets/7287076/13493889/bc1565b8-e138-11e5-8db3-2b81a217ba6b.png)

But only after I replaced the previous `math.js` with this (which I found in another open issue here):

``` js
const seneca = require('seneca')();

const math = function (options) {
  this.add('role:math, cmd:sum', function (msg, respond) {
    var sum = msg.left + msg.right
    respond(null, {answer: sum})
  })
}
module.exports = math
```

And yet the verify still can't find the plugin:
![image](https://cloud.githubusercontent.com/assets/7287076/13493939/26aa0848-e139-11e5-8374-c3d95df82708.png)

**Comment by piccoloaiutante** [comment]
Thanks @batjko i'l have a look at it this week.

**Comment by iiiw** [comment]
Same here. Plus, I am not sure about: "The client must add the number passed as parameters (use process.argv)". To call the service we need two numbers; probably it should be "numbers" (plural).

**Comment by piccoloaiutante** [comment]
@iiw @batjko @marcopiraccini do you want to have quick check before i merge it ?

https://github.com/senecajs/seneca-in-practice/pull/26

**Comment by piccoloaiutante** [comment]
it should be fixed in version 0.1.11

**Comment by iiiw** [comment]
In the description – but not in your revised solution – there is still 
the line `seneca.use('math')` which gives me a fatal error if I leave it 
in the file. If I comment it out, I can call the service.

But I don't get any numbers passed via process.argv.
Instead I get two strings, so the result value is the concatenation 
(Javascript doesn't complain) of two paths:
`{ answer: 
'/path/to/dev/node/nodeschool/seneca/myclient.js--seneca.log.quiet' }`
If I insert random numbers everything works as expected, but I cannot 
verify the submission without looking up the numbers in the solution.

Here is my client.js:

```
// jshint esversion: 6, node: true, strict: true

'use strict';

const seneca = require('./math');

const nl = process.argv[2], nr = process.argv[3];

//seneca.use('math');

seneca.act({role:"math",cmd:"sum",left:nl,right:nr}, (err, result) => {
     if (err) throw err;
     console.log(result);
});

module.exports = seneca;
```

**Comment by piccoloaiutante** [comment]
@iiiw you're right i forgot to add process.argv support for that exercise. Can you check this PR:

https://github.com/senecajs/seneca-in-practice/pull/27

this should solve your problem.
