### ISSUE TITLE
Can't validate transport solution

### ISSUE THREAD

**Issue by mihaidma** [senecajs/seneca-in-practice#74]
If I try to validate the solution located in the "Transport" lesson I get an error:

```
seneca-in-practice verify ./problems/transport/solution/solution.js
Invoking sum with random generated: 38, 31:
{"kind":"notice","notice":"seneca started","level":"info","when":1475502445469}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:25602
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

if I log the argv received:

```
argv:  [ ...node/v6.5.0/bin/node',
  '.../seneca/seneca-in-practice/problems/transport/solution/solution.js',
  '25602' ]
```

The code uses argv[2] for port:

```
require('seneca')().use('./math').listen({
  port: process.argv[2],
  host: '127.0.0.1'
})
```

If I run `node  ./problems/transport/solution/solution.js 25602` it starts correctly:

```
node  ./problems/transport/solution/solution.js 25602
{"kind":"notice","notice":"seneca started","level":"info","when":1475502665508}
```

then I verify that it works:

```
curl -d '{"cmd":"sum","left":1,"right":2}' http://localhost:25602/act?role=math
{"answer":3,"info":"1 + 2"}
```

**Comment by mihaidma** [comment]
solved in the latest version
