### ISSUE TITLE
can't run exercises

### ISSUE THREAD

**Issue by Cbenh** [senecajs/seneca-in-practice#97]
I cant run any exercises from graphic interface with command ` seneca-in-practice` or from command line with `seneca-in-practice select Sum`.

` /usr/local/lib/node_modules/seneca-in-practice/problems/sum/exercise.js:8
const {getRandomInt} = require('../utils')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Workshopper.loadExercise (/usr/local/lib/node_modules/seneca-in-practice/node_modules/workshopper/workshopper.js:484:14)
    at Workshopper.onselect (/usr/local/lib/node_modules/seneca-in-practice/node_modules/workshopper/workshopper.js:501:23)
    at new Workshopper (/usr/local/lib/node_modules/seneca-in-practice/node_modules/workshopper/workshopper.js:142:14) `

**Comment by tswaters** [comment]
Destructured assignment requires node 6+

**Comment by marcopiraccini** [comment]
OK, but maybe we should specify better the supported node version. 
Reopening and labeling as enhancement.
